---
# tasks file for deploy-app

- name: Create the app folder
  file: path={{ app_basedir }} owner={{ app_files_owner }} group={{ app_files_group }} mode=0775 state=directory

- name: Copy the app JAR
  copy:
    src: "{{ app_jar_file }}"
    dest: "{{ app_basedir }}/{{ app_jar_file }}"
    owner: "{{ app_files_owner }}"
    group: "{{ app_files_group }}"
  notify:
    - Restart sancho service

- name: Create the current version symlink
  file:
    src: "{{ app_basedir }}/{{ app_jar_file }}"
    dest: "{{ app_basedir }}/{{ app_current_jar_symlink }}"
    owner: "{{ app_files_owner }}"
    group: "{{ app_files_group }}"
    state: link
  notify:
    - Restart sancho service

- name: Delete old JARs
  script: delete_old_jars.sh {{ app_basedir }} {{ num_old_jars_to_keep }}

- name: Copy application.yml file
  template:
    src: "{{ app_properties_src }}"
    dest: "{{ app_basedir }}/application.yml"
    owner: "{{ app_files_owner }}"
    group: "{{ app_files_group }}"
  notify:
    - Restart sancho service

- name: Copy sancho.yml file
  template:
    src: "{{ sancho_properties_src }}"
    dest: "{{ app_basedir }}/sancho.yml"
    owner: "{{ app_files_owner }}"
    group: "{{ app_files_group }}"
  notify:
    - Restart sancho service

- name: Copy the systemd service unit
  template:
    src: sancho.service.j2
    dest: /etc/systemd/system/sancho.service
    owner: root
    group: root
  notify:
    - Reload systemd unit files
    - Restart sancho service

- name: sancho service must be started and enabled on boot
  service:
    name: sancho
    state: started
    enabled: yes
